#ifndef HEADER_IMAGE
#define HEADER_IMAGE
#include <stdlib.h>
#include<stdio.h>




typedef enum { false, true } bool;
//function to write the image from a Grid
void write_pgm_image( void *image, int xsize,int ysize, const char *image_name)
{
const int maxval=255;
FILE* image_file;
image_file=fopen(image_name,"w");
fprintf(image_file, "P5\n#generated by\n#Enrico Malcapi\n%d %d\n%d\n", ysize, xsize, maxval);// Writing the header and the dimensions following the PGM format
fwrite(image,1,xsize*ysize,image_file);//writing the image in 1 line
fclose(image_file);
};

//Function to read the image from a grid
void* read_pgm_image(int* xsize,int*ysize,const char*image_name){
void* image;
*xsize=0;
*ysize=0;
FILE* image_file;
char*line=NULL;
size_t k=0,n=0;
image_file=fopen(image_name,"r");
// getline(&buffer,&sizebuffer,std) assign to the buffer of size=sizebuffer what is writtend in a 1 line of the std indicated 
for (int i=0;i<4;i++)
  k=getline( &line, &n, image_file);// skip the header unitll i find my self into the line containing the dimensions


sscanf(line,"%d %d", ysize, xsize);// read the dimensions
k=getline( &line, &n, image_file);//skip the max value line
k=getline( &line, &n, image_file);// Now i find my self on the line containing the image
image=(void*)line;
fclose(image_file);
return image;
};



//Function that create the initial set up 
void* create_image(const int x_size,const int y_size,const int total_dim,const int rank)
{

void*ptr;
char *image;
int dim=x_size*y_size;
int dim_4=total_dim/4;
int quarto=total_dim/4;
image=(char*)calloc( dim, sizeof(char) );
for (int i = 0;i<x_size;i++){
    for (int j=0;j<y_size;j++){
    if((x_size*rank+i>dim_4 & x_size*rank+i<3*dim_4)&(j>quarto & j<3*quarto)){image[j+i*y_size]=(char)0;}
    else{image[j+i*y_size]=(char)255;}
    }
}



ptr=(void*)image;
return ptr;
};
//Function used to create the scaled image 
void color(char* image,char* grid,int cell_size,int y_size,int row,int column){
for(int i=0;i<cell_size;i++){
    for(int j=0;j<cell_size;j++){
        image[(column*cell_size+j)+(row*cell_size+i)*cell_size*y_size]=grid[column+row*y_size];
    }
}
};

//Function used to check the existence of a file
bool file_exists(const char *filename)
{
    FILE *fp = fopen(filename, "r");
    bool is_exist = false;
    if (fp != NULL)
    {
        is_exist = true;
        fclose(fp); // close the file
    }
    return is_exist;
};







#endif
